# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.10

    working_directory: ~/app

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: Install dependencies
          command: |
            npm cache clean --force
            npm install -f -d --quiet --loglevel=warn
      # Step 3: run linter and tests
      - run:
          name: Run tests
          command: npm run-script test
  deploy:
    docker:
      - image: wecs/circle-ci-gcloud-node:0.1.0
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy
          command: ./deployment.sh

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
