apiVersion: v1
kind: Service
metadata:
  name: circle-service
  labels:
    app: circle
spec:
  ports:
    - targetPort: 3000
      port: 80
  selector:
    app: ci-deploy
    tier: backend
  type: LoadBalancer
