apiVersion: apps/v1
kind: Deployment
metadata:
  name: circle-demo
  labels:
    app: simple-backend
spec:
  selector:
    matchLabels:
      app: ci-deploy
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ci-deploy
        tier: backend
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/winter-cogency-307316/test-registry/test:1.0.0
          name: test
          ports:
            - containerPort: 3000
              name: ci-deploy
